### ISSUE TITLE
Pico version 2

### ISSUE THREAD

**Issue by jayhawkins** [RWDevelopment/theme_switch#1]
I can get this working with Pico V1, but my svg images do not show with Pico V2. I know this is an issue with Pico and how it may now handle svg data formats, just wanted to let you know.

**Comment by RWDevelopment** [comment]
change head style to
 `<style>
    header nav li a svg {
      width: 1rem;
      height: 1rem;
      color: var(--pico-contrast);
    }
    </style>`
